apiVersion: apps/v1
kind: Deployment
metadata:
  name: sumitg2386/fastapi-app:latest
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: sumitg2386/fastapi-app:latest
        image: sumitg2386/fastapi-app:latest:latest  # Replace with your Docker image
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort