name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sumitg2386/fastapi-app:latest

      - name: Kubernetes Manifest Update
        run: |
          sed -i "s|fastapi-app|${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest|" manifests/deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifests/deployment.yaml
          git commit -m "Update Kubernetes manifest with new Docker image"
          git push
