name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:          
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      image_tag:
        description: 'Docker Image Tag (leave empty for default SHA)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      
      - name: Build and Push Docker Image
        run: |
          SHA=$(echo $GITHUB_SHA | cut -c1-7)  
          if [[ -n "${{ inputs.image_tag }}" ]]; then
            SHA=${{ inputs.image_tag }}
          fi
          echo "SHA=$SHA" >> $GITHUB_ENV
          
          # Build with both SHA and latest tags
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:$SHA .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
          
          # Push both images
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:$SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Kubernetes Manifest Update
        run: |
          sed -i "s|${{ secrets.DOCKER_USERNAME }}/fastapi-app:.*|${{ secrets.DOCKER_USERNAME }}/fastapi-app:$SHA|" manifests/deployment.yaml


      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        
          git add manifests/deployment.yaml
          git commit -m "Update Kubernetes manifest with new Docker image"
          git push
